### ISSUE TITLE
8月9日(月)の出来具合

### ISSUE THREAD

**Issue by sataga** [sataga/go-template-sample#1]
## 実行ログ
```
 t-sataga@MBA  ~/go/src/github.com/sataga/go-template-sample   master ± 
-> % go run main.go                                                                                                        01:28:06 - 01:30:53
apiVersion: apps/v1
kind: mp
metadata:
  name: tgsl-ssk-tgsk8s1-tgs-cs-ur-stage
  namespace: bp
spec:
  oc:
    authURL: https://keystone-public.tgsl-ssk-tgsk8s1-ro.com
  az:
  - name: a
    zoneName: A_tgsl-ssk-tgsk8s1-ro
  - name: b
    zoneName: B_tgsl-ssk-tgsk8s1-ro
  flavors:
    - name: hoge-flavor
      id: 123-abc-flavor
    - name: hoge-flavor
      id: 456-def-flavor
    - name: hoge-flavor
      id: 789-ghi-flavor
    networks:
  - name: 123-abc-master-subnet
    networkName: 123-abc-master-subnet
    networkID:hoge-userk8s
    group: prod-ssk-tgsk8s1--share
  lb:
  - name: external-456-def-ingress-subnet
    subnetID: hoge-ingress
    provider: lb2
    maxConcurrentRequests: 5
  - name: internal-123-abc-master-subnet
    subnetID: hoge-master
    provider: lb2
    maxConcurrentRequests: 5
  region:
  tenant: tgs-cs-ur-stage
  domainName: Default
  username: headless.stage-bp
```

**Comment by sataga** [comment]
>   username: headless.stage-bp

stgが正しい

**Comment by sataga** [comment]
修正後
```
apiVersion: apps/v1
kind: mp
metadata:
  name: tgsl-ssk-tgsk8s1-tgs-cs-ur-stage
  namespace: bp
spec:
  oc:
    authURL: https://keystone-public.tgsl-ssk-tgsk8s1-ro.com
  az:
  - name: a
    zoneName: A_tgsl-ssk-tgsk8s1-ro
  - name: b
    zoneName: B_tgsl-ssk-tgsk8s1-ro
  flavors:
    - name: hoge-flavor
      id: 123-abc-flavor
    - name: hoge-flavor
      id: 456-def-flavor
    - name: hoge-flavor
      id: 789-ghi-flavor
    networks:
  - name: 123-abc-master-subnet
    networkName: 123-abc-master-subnet
    networkID:hoge-userk8s
    group: prod-ssk-tgsk8s1--share
  lb:
  - name: external-456-def-ingress-subnet
    subnetID: hoge-ingress
    provider: lb2
    maxConcurrentRequests: 5
  - name: internal-123-abc-master-subnet
    subnetID: hoge-master
    provider: lb2
    maxConcurrentRequests: 5
  region:
  tenant: tgs-cs-ur-stage
  domainName: Default
  username: headless.stg-bp
```

**Comment by sataga** [comment]
>     networks:

微妙にずれる。。{{ end -}} の - のせい。
外すと改行が入ってしまうがしゃーない

**Comment by sataga** [comment]
修正後
```
apiVersion: apps/v1
kind: mp
metadata:
  name: tgsl-ssk-tgsk8s1-tgs-cs-ur-stage
  namespace: bp
spec:
  oc:
    authURL: https://keystone-public.tgsl-ssk-tgsk8s1-ro.com
  az:
  - name: a
    zoneName: A_tgsl-ssk-tgsk8s1-ro
  - name: b
    zoneName: B_tgsl-ssk-tgsk8s1-ro
  flavors:
    - name: hoge-flavor
      id: 123-abc-flavor
    - name: hoge-flavor
      id: 456-def-flavor
    - name: hoge-flavor
      id: 789-ghi-flavor
    
  networks:
  - name: 123-abc-master-subnet
    networkName: 123-abc-master-subnet
    networkID:hoge-userk8s
    group: prod-ssk-tgsk8s1--share
  lb:
  - name: external-456-def-ingress-subnet
    subnetID: hoge-ingress
    provider: lb2
    maxConcurrentRequests: 5
  - name: internal-123-abc-master-subnet
    subnetID: hoge-master
    provider: lb2
    maxConcurrentRequests: 5
  region:
  tenant: tgs-cs-ur-stage
  domainName: Default
  username: headless.stg-bp
    

```
